In [186]:
import pandas as pd
import numpy as np

In [187]:
data = pd.read_csv("test.csv")
data

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x2595b,CUS_0x3e03,June,Martinne Gellerj,23,504-67-6939,Developer,35971.49,NaN,5,...,_,132.82,39.548192,27 Years and 8 Months,Yes,54.481740,NaN,Low_spent_Small_value_payments,176.4421072,NaN
1,0xa2e2,CUS_0x3615,May,Samb,27,959-59-4160,Accountant,122425.8_,10001.150000,4,...,Standard,1252.3,39.469381,23 Years and 8 Months,Yes,148.188179,254.8090706,High_spent_Medium_value_payments,847.1177504,NaN
2,0x131cd,CUS_0x9122,April,Stanley Whitei,36,975-98-6988,Engineer,19773.56,1939.796667,4,...,_,1019.48,29.769062,23 Years and 1 Months,NM,10.358307,__10000__,Low_spent_Small_value_payments,294.0033384,NaN
3,0x1bced,CUS_0x3371,April,Maciejv,19,581-39-0550,Architect,61632.99,NaN,9,...,Bad,1634.98,31.566848,9 Years and 6 Months,Yes,311.564961,313.1820203,Low_spent_Medium_value_payments,140.8612683,NaN
4,0x1ee87,CUS_0xecc,June,Papadimase,25,248-56-1152,Lawyer,9413.305,1072.442083,8,...,Standard,1746.62,35.225618,NaN,Yes,32.742096,40.03202937,Low_spent_Medium_value_payments,314.4700825,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,0x3ab7,CUS_0x36f9,February,Lucy Hornbyr,46,992-38-5349,Developer,82065.16,6771.763333,5,...,Good,106.83,35.131041,23 Years and 0 Months,No,180.340607,439.8401794,High_spent_Small_value_payments,316.9955472,NaN
19996,0x15798,CUS_0x70a3,July,Islan,20,291-89-8959,Accountant,14920.97,1424.414167,6,...,Standard,1288.58,33.572279,13 Years and 5 Months,Yes,19.909512,110.0842395,Low_spent_Small_value_payments,302.4476647,NaN
19997,0x1d81e,CUS_0x1cf3,May,Henryc,38,229-46-4057,Manager,66858.27,5770.522500,3,...,Standard,601.58,37.982933,28 Years and 1 Months,NM,175.015182,364.7070519,Low_spent_Medium_value_payments,317.3300163,NaN
19998,0x1b0a,CUS_0x2c0d,May,ernieh,55_,784-23-6447,Doctor,19403.405_,1904.950417,1,...,_,339.11,36.826610,16 Years and 8 Months,No,39.214914,169.8581974,Low_spent_Large_value_payments,251.4219299,NaN
19999,0x728d,CUS_0x79d5,April,Tomx,33,788-50-6387,Architect,19171.68,NaN,10,...,Bad,2092.74,37.579855,11 Years and 6 Months,NM,92.590913,52.61391515,Low_spent_Small_value_payments,286.1591718,NaN

Data Manipulation

In [188]:
# reset ID
data['ID'] = data.index+1

In [189]:
# check Null
check_null = pd.DataFrame(columns=['num_null', 'percent_null'])
check_null['num_null'] = data.isnull().sum()
check_null['percent_null'] = round(check_null['num_null'] / len(data) *100,2)
check_null

                          num_null  percent_null
ID                               0          0.00
Customer_ID                      0          0.00
Month                            0          0.00
Name                          1977          9.88
Age                              0          0.00
SSN                              0          0.00
Occupation                       0          0.00
Annual_Income                    0          0.00
Monthly_Inhand_Salary         3040         15.20
Num_Bank_Accounts                0          0.00
Num_Credit_Card                  0          0.00
Interest_Rate                    0          0.00
Num_of_Loan                      0          0.00
Type_of_Loan                  2195         10.98
Delay_from_due_date              0          0.00
Num_of_Delayed_Payment        1374          6.87
Changed_Credit_Limit             0          0.00
Num_Credit_Inquiries           386          1.93
Credit_Mix                       0          0.00
Outstanding_Debt                 0          0.00
Credit_Utilization_Ratio         0          0.00
Credit_History_Age            1807          9.04
Payment_of_Min_Amount            0          0.00
Total_EMI_per_month              0          0.00
Amount_invested_monthly        949          4.74
Payment_Behaviour                0          0.00
Monthly_Balance                259          1.30
Credit_Score                 20000        100.00

In [190]:
print(f"Original shape of data: {data.shape}")
print(f"New shape of data after dropping nulls: {data.dropna(inplace=False).shape}")

Original shape of data: (20000, 28)
New shape of data after dropping nulls: (0, 28)

In [191]:
data

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,1,CUS_0x3e03,June,Martinne Gellerj,23,504-67-6939,Developer,35971.49,NaN,5,...,_,132.82,39.548192,27 Years and 8 Months,Yes,54.481740,NaN,Low_spent_Small_value_payments,176.4421072,NaN
1,2,CUS_0x3615,May,Samb,27,959-59-4160,Accountant,122425.8_,10001.150000,4,...,Standard,1252.3,39.469381,23 Years and 8 Months,Yes,148.188179,254.8090706,High_spent_Medium_value_payments,847.1177504,NaN
2,3,CUS_0x9122,April,Stanley Whitei,36,975-98-6988,Engineer,19773.56,1939.796667,4,...,_,1019.48,29.769062,23 Years and 1 Months,NM,10.358307,__10000__,Low_spent_Small_value_payments,294.0033384,NaN
3,4,CUS_0x3371,April,Maciejv,19,581-39-0550,Architect,61632.99,NaN,9,...,Bad,1634.98,31.566848,9 Years and 6 Months,Yes,311.564961,313.1820203,Low_spent_Medium_value_payments,140.8612683,NaN
4,5,CUS_0xecc,June,Papadimase,25,248-56-1152,Lawyer,9413.305,1072.442083,8,...,Standard,1746.62,35.225618,NaN,Yes,32.742096,40.03202937,Low_spent_Medium_value_payments,314.4700825,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,CUS_0x36f9,February,Lucy Hornbyr,46,992-38-5349,Developer,82065.16,6771.763333,5,...,Good,106.83,35.131041,23 Years and 0 Months,No,180.340607,439.8401794,High_spent_Small_value_payments,316.9955472,NaN
19996,19997,CUS_0x70a3,July,Islan,20,291-89-8959,Accountant,14920.97,1424.414167,6,...,Standard,1288.58,33.572279,13 Years and 5 Months,Yes,19.909512,110.0842395,Low_spent_Small_value_payments,302.4476647,NaN
19997,19998,CUS_0x1cf3,May,Henryc,38,229-46-4057,Manager,66858.27,5770.522500,3,...,Standard,601.58,37.982933,28 Years and 1 Months,NM,175.015182,364.7070519,Low_spent_Medium_value_payments,317.3300163,NaN
19998,19999,CUS_0x2c0d,May,ernieh,55_,784-23-6447,Doctor,19403.405_,1904.950417,1,...,_,339.11,36.826610,16 Years and 8 Months,No,39.214914,169.8581974,Low_spent_Large_value_payments,251.4219299,NaN
19999,20000,CUS_0x79d5,April,Tomx,33,788-50-6387,Architect,19171.68,NaN,10,...,Bad,2092.74,37.579855,11 Years and 6 Months,NM,92.590913,52.61391515,Low_spent_Small_value_payments,286.1591718,NaN

Dealing with null

In [192]:
update_data = data.copy()

In [193]:
# check Null
check_null = pd.DataFrame(columns=['num_null', 'percent_null'])
check_null['num_null'] = update_data.isnull().sum()
check_null['percent_null'] = round(check_null['num_null'] / len(update_data) *100,2)
check_null

                          num_null  percent_null
ID                               0          0.00
Customer_ID                      0          0.00
Month                            0          0.00
Name                          1977          9.88
Age                              0          0.00
SSN                              0          0.00
Occupation                       0          0.00
Annual_Income                    0          0.00
Monthly_Inhand_Salary         3040         15.20
Num_Bank_Accounts                0          0.00
Num_Credit_Card                  0          0.00
Interest_Rate                    0          0.00
Num_of_Loan                      0          0.00
Type_of_Loan                  2195         10.98
Delay_from_due_date              0          0.00
Num_of_Delayed_Payment        1374          6.87
Changed_Credit_Limit             0          0.00
Num_Credit_Inquiries           386          1.93
Credit_Mix                       0          0.00
Outstanding_Debt                 0          0.00
Credit_Utilization_Ratio         0          0.00
Credit_History_Age            1807          9.04
Payment_of_Min_Amount            0          0.00
Total_EMI_per_month              0          0.00
Amount_invested_monthly        949          4.74
Payment_Behaviour                0          0.00
Monthly_Balance                259          1.30
Credit_Score                 20000        100.00

Name

In [194]:
update_data['Name'] = update_data['Name'].str.replace(r'[^A-Za-z ]', '', regex=True)

In [195]:
update_data['Name'] = (update_data.groupby('Customer_ID')['Name'].transform(lambda x: x.ffill().bfill()))
update_data['Name'] = update_data['Name'].fillna("NO_INFORM")
print(f"Nulls in 'Name' after imputation: {update_data['Name'].isnull().sum()}")

Nulls in 'Name' after imputation: 0

In [196]:
update_data = update_data.sort_values(by=['Customer_ID', 'Name', 'Month']).reset_index(drop=True)
update_data['ID'] = update_data.index + 1
display(update_data.head())

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,1,CUS_0x1000,August,Alistair Barrf,18,913-74-1218,Lawyer,30625.94,2706.161667,6,...,Bad,1562.91,30.077191,10 Years and 9 Months,Yes,42.941090,77.31427572,High_spent_Medium_value_payments,400.3608005,NaN
1,2,CUS_0x1000,March,Alistair Barrf,17_,913-74-1218,Lawyer,30625.94_,2706.161667,6,...,Bad,1562.91,38.285928,10 Years and 4 Months,Yes,42.941090,109.0565188,High_spent_Medium_value_payments,368.6185575,NaN
2,3,CUS_0x1009,January,Arunah,25,#F%$D@*&8,Mechanic,52312.68,4250.390000,6,...,Standard,202.68,23.679534,30 Years and 5 Months,NM,108.366467,261.2109794,Low_spent_Medium_value_payments,335.4615535,NaN
3,4,CUS_0x100b,January,Shirboni,18,238-62-0395,Media_Manager,113781.39,9549.782500,1,...,Good,1030.2,37.998760,15 Years and 3 Months,No,0.000000,397.2418458,Low_spent_Medium_value_payments,837.7364042,NaN
4,5,CUS_0x100b,May,Shirboni,19,238-62-0395,Media_Manager,113781.39,9549.782500,1,...,Good,1030.2,32.035662,15 Years and 7 Months,No,0.000000,758.0831955,Low_spent_Small_value_payments,486.8950545,NaN

Monthly_Inhand_Salary

In [197]:
update_data['Monthly_Inhand_Salary'] = (update_data.groupby(['Customer_ID', 'Name'])['Monthly_Inhand_Salary'].transform(lambda x: x.ffill().bfill() if x.notna().any() else 'NO_INFORM'))

# Check the number of nulls in 'Monthly_Inhand_Salary' after imputation
print(f"Nulls in 'Monthly_Inhand_Salary' after imputation: {update_data['Monthly_Inhand_Salary'].isnull().sum()}")

Nulls in 'Monthly_Inhand_Salary' after imputation: 0

In [198]:
update_data['Monthly_Inhand_Salary'] = pd.to_numeric(update_data['Monthly_Inhand_Salary'], errors='coerce')

global_median = update_data['Monthly_Inhand_Salary'].median()

update_data['Monthly_Inhand_Salary'] = (
    update_data.groupby(['Customer_ID', 'Name'])['Monthly_Inhand_Salary']
    .transform(lambda x: x.fillna(x.median()) if x.notna().any() else global_median)
)

# Check the number of nulls after imputation
print(f"Nulls in 'Monthly_Inhand_Salary' after imputation: {update_data['Monthly_Inhand_Salary'].isnull().sum()}")

Nulls in 'Monthly_Inhand_Salary' after imputation: 0

Type_of_Loan

In [199]:
update_data[update_data['Type_of_Loan'].isnull()][['ID', 'Customer_ID', 'Month', 'Name', 'Type_of_Loan']].head(10)

    ID Customer_ID     Month                Name Type_of_Loan
3    4  CUS_0x100b   January            Shirboni          NaN
4    5  CUS_0x100b       May            Shirboni          NaN
7    8  CUS_0x1015     April             Holtono          NaN
8    9  CUS_0x1015    August             Holtono          NaN
9   10  CUS_0x1015      July             Holtono          NaN
10  11  CUS_0x1015       May             Holtono          NaN
28  29  CUS_0x1044     April       Maki Shirakip          NaN
29  30  CUS_0x1044       May       Maki Shirakip          NaN
39  40  CUS_0x105b  February  Patricia Zengerlel          NaN
40  41  CUS_0x105b      July  Patricia Zengerlel          NaN

In [200]:
update_data['Type_of_Loan'] = (update_data.groupby(['Customer_ID', 'Name'])['Type_of_Loan'].transform(lambda x: x.ffill().bfill() if x.notna().any() else 'NO_INFORM'))

# Check the number of nulls in 'Type_of_Loan' after imputation
print(f"Nulls in 'Type_of_Loan' after imputation: {update_data['Type_of_Loan'].isnull().sum()}")

Nulls in 'Type_of_Loan' after imputation: 0

In [201]:
display(update_data[update_data['Name'].isin(['Shirboni'])][['ID', 'Customer_ID', 'Month', 'Name', 'Type_of_Loan']])

   ID Customer_ID    Month      Name Type_of_Loan
3   4  CUS_0x100b  January  Shirboni    NO_INFORM
4   5  CUS_0x100b      May  Shirboni    NO_INFORM

Num_of_Delayed_Payment

In [202]:
update_data['Num_of_Delayed_Payment'] = pd.to_numeric(update_data['Num_of_Delayed_Payment'], errors='coerce')

global_median = update_data['Num_of_Delayed_Payment'].median()

update_data['Num_of_Delayed_Payment'] = (
    update_data.groupby(['Customer_ID', 'Name'])['Num_of_Delayed_Payment']
    .transform(lambda x: x.fillna(x.median()) if x.notna().any() else global_median)
)

# Check the number of nulls after imputation
print(f"Nulls in 'Num_of_Delayed_Payment' after imputation: {update_data['Num_of_Delayed_Payment'].isnull().sum()}")

Nulls in 'Num_of_Delayed_Payment' after imputation: 0

Num_Credit_Inquiries

In [203]:
update_data['Num_Credit_Inquiries'] = pd.to_numeric(update_data['Num_Credit_Inquiries'], errors='coerce')

global_median = update_data['Num_Credit_Inquiries'].median()

update_data['Num_Credit_Inquiries'] = (
    update_data.groupby(['Customer_ID', 'Name'])['Num_Credit_Inquiries']
    .transform(lambda x: x.fillna(x.median()) if x.notna().any() else global_median)
)

# Check the number of nulls after imputation
print(f"Nulls in 'Num_Credit_Inquiries' after imputation: {update_data['Num_Credit_Inquiries'].isnull().sum()}")

Nulls in 'Num_Credit_Inquiries' after imputation: 0

Amount_invested_monthly

In [204]:
update_data['Amount_invested_monthly'] = (update_data['Amount_invested_monthly'].astype(str).str.replace(r'[^0-9.]', '', regex=True))
update_data['Amount_invested_monthly'] = pd.to_numeric(update_data['Amount_invested_monthly'], errors='coerce')

In [205]:
global_median = update_data['Amount_invested_monthly'].median()

update_data['Amount_invested_monthly'] = (
    update_data.groupby(['Customer_ID', 'Name'])['Amount_invested_monthly']
    .transform(lambda x: x.fillna(x.median()) if x.notna().any() else global_median)
)

# Check the number of nulls after imputation
print(f"Nulls in 'Amount_invested_monthly' after imputation: {update_data['Amount_invested_monthly'].isnull().sum()}")

Nulls in 'Amount_invested_monthly' after imputation: 0

Monthly_Balance

In [206]:
update_data['Monthly_Balance'] = pd.to_numeric(update_data['Monthly_Balance'], errors='coerce')

global_median = update_data['Monthly_Balance'].median()

update_data['Monthly_Balance'] = (
    update_data.groupby(['Customer_ID', 'Name'])['Monthly_Balance']
    .transform(lambda x: x.fillna(x.median()) if x.notna().any() else global_median)
)

# Check the number of nulls after imputation
print(f"Nulls in 'Monthly_Balance' after imputation: {update_data['Monthly_Balance'].isnull().sum()}")

Nulls in 'Monthly_Balance' after imputation: 0

Credit_History_Age

In [207]:
update_data['Credit_History_Age'].unique()

array(['10 Years and 9 Months', '10 Years and 4 Months',
       '30 Years and 5 Months', '15 Years and 3 Months',
       '15 Years and 7 Months', '17 Years and 4 Months',
       '21 Years and 1 Months', '21 Years and 5 Months',
       '21 Years and 4 Months', '21 Years and 2 Months',
       '20 Years and 8 Months', '30 Years and 3 Months',
       '29 Years and 9 Months', '29 Years and 8 Months',
       '30 Years and 2 Months', '30 Years and 1 Months', nan,
       '22 Years and 10 Months', '16 Years and 3 Months',
       '15 Years and 10 Months', '19 Years and 5 Months',
       '19 Years and 9 Months', '26 Years and 9 Months',
       '9 Years and 10 Months', '31 Years and 7 Months',
       '31 Years and 8 Months', '9 Years and 11 Months',
       '31 Years and 9 Months', '25 Years and 0 Months',
       '24 Years and 9 Months', '24 Years and 11 Months',
       '14 Years and 7 Months', '14 Years and 8 Months',
       '28 Years and 1 Months', '15 Years and 11 Months',
       '27 Years and 5 Months', '23 Years and 9 Months',
       '24 Years and 2 Months', '16 Years and 5 Months',
       '16 Years and 10 Months', '16 Years and 8 Months',
       '30 Years and 7 Months', '17 Years and 8 Months',
       '14 Years and 0 Months', '13 Years and 5 Months',
       '12 Years and 0 Months', '11 Years and 6 Months',
       '11 Years and 11 Months', '11 Years and 10 Months',
       '28 Years and 0 Months', '28 Years and 2 Months',
       '7 Years and 2 Months', '7 Years and 8 Months',
       '7 Years and 6 Months', '20 Years and 9 Months',
       '20 Years and 11 Months', '19 Years and 11 Months',
       '20 Years and 0 Months', '6 Years and 2 Months',
       '6 Years and 0 Months', '6 Years and 1 Months',
       '29 Years and 6 Months', '15 Years and 9 Months',
       '15 Years and 2 Months', '15 Years and 8 Months',
       '16 Years and 2 Months', '16 Years and 0 Months',
       '27 Years and 0 Months', '27 Years and 3 Months',
       '27 Years and 2 Months', '18 Years and 0 Months',
       '12 Years and 11 Months', '29 Years and 10 Months',
       '29 Years and 7 Months', '12 Years and 2 Months',
       '21 Years and 0 Months', '21 Years and 3 Months',
       '7 Years and 1 Months', '10 Years and 7 Months',
       '31 Years and 11 Months', '30 Years and 4 Months',
       '19 Years and 7 Months', '14 Years and 1 Months',
       '6 Years and 5 Months', '6 Years and 10 Months',
       '8 Years and 9 Months', '8 Years and 8 Months',
       '8 Years and 7 Months', '16 Years and 11 Months',
       '16 Years and 9 Months', '19 Years and 4 Months',
       '23 Years and 3 Months', '23 Years and 5 Months',
       '26 Years and 11 Months', '13 Years and 11 Months',
       '30 Years and 10 Months', '26 Years and 1 Months',
       '25 Years and 2 Months', '30 Years and 8 Months',
       '17 Years and 11 Months', '27 Years and 9 Months',
       '10 Years and 10 Months', '8 Years and 2 Months',
       '8 Years and 5 Months', '8 Years and 4 Months',
       '23 Years and 7 Months', '25 Years and 6 Months',
       '25 Years and 3 Months', '28 Years and 7 Months',
       '28 Years and 5 Months', '28 Years and 8 Months',
       '18 Years and 7 Months', '18 Years and 8 Months',
       '19 Years and 8 Months', '17 Years and 5 Months',
       '17 Years and 2 Months', '10 Years and 5 Months',
       '18 Years and 9 Months', '24 Years and 4 Months',
       '24 Years and 3 Months', '20 Years and 1 Months',
       '19 Years and 10 Months', '25 Years and 9 Months',
       '19 Years and 1 Months', '32 Years and 11 Months',
       '33 Years and 2 Months', '33 Years and 1 Months',
       '32 Years and 10 Months', '9 Years and 0 Months',
       '8 Years and 6 Months', '8 Years and 11 Months',
       '14 Years and 4 Months', '14 Years and 5 Months',
       '9 Years and 1 Months', '9 Years and 2 Months',
       '22 Years and 3 Months', '17 Years and 3 Months',
       '21 Years and 8 Months', '21 Years and 7 Months',
       '31 Years and 10 Months', '32 Years and 0 Months',
       '18 Years and 2 Months', '18 Years and 6 Months',
       '2 Years and 4 Months', '23 Years and 8 Months',
       '23 Years and 1 Months', '13 Years and 4 Months',
       '13 Years and 8 Months', '22 Years and 1 Months',
       '17 Years and 1 Months', '14 Years and 6 Months',
       '14 Years and 9 Months', '5 Years and 11 Months',
       '5 Years and 8 Months', '11 Years and 5 Months',
       '11 Years and 4 Months', '31 Years and 5 Months',
       '22 Years and 7 Months', '5 Years and 1 Months',
       '4 Years and 10 Months', '5 Years and 0 Months',
       '13 Years and 2 Months', '13 Years and 1 Months',
       '19 Years and 6 Months', '19 Years and 3 Months',
       '13 Years and 3 Months', '24 Years and 0 Months',
       '31 Years and 4 Months', '31 Years and 3 Months',
       '31 Years and 1 Months', '15 Years and 1 Months',
       '15 Years and 0 Months', '5 Years and 5 Months',
       '5 Years and 4 Months', '5 Years and 10 Months',
       '5 Years and 9 Months', '1 Years and 11 Months',
       '1 Years and 4 Months', '1 Years and 9 Months',
       '19 Years and 0 Months', '17 Years and 10 Months',
       '3 Years and 10 Months', '6 Years and 4 Months',
       '27 Years and 10 Months', '13 Years and 0 Months',
       '22 Years and 4 Months', '30 Years and 6 Months',
       '28 Years and 10 Months', '29 Years and 3 Months',
       '26 Years and 10 Months', '12 Years and 10 Months',
       '12 Years and 9 Months', '7 Years and 4 Months',
       '13 Years and 7 Months', '30 Years and 0 Months',
       '24 Years and 8 Months', '22 Years and 6 Months',
       '9 Years and 7 Months', '9 Years and 5 Months',
       '9 Years and 8 Months', '7 Years and 11 Months',
       '29 Years and 5 Months', '15 Years and 6 Months',
       '14 Years and 11 Months', '21 Years and 6 Months',
       '25 Years and 5 Months', '32 Years and 5 Months',
       '11 Years and 8 Months', '32 Years and 7 Months',
       '18 Years and 5 Months', '8 Years and 10 Months',
       '15 Years and 4 Months', '26 Years and 3 Months',
       '25 Years and 11 Months', '10 Years and 0 Months',
       '16 Years and 6 Months', '14 Years and 3 Months',
       '11 Years and 0 Months', '33 Years and 4 Months',
       '26 Years and 7 Months', '31 Years and 2 Months',
       '31 Years and 0 Months', '18 Years and 1 Months',
       '12 Years and 4 Months', '19 Years and 2 Months',
       '12 Years and 5 Months', '12 Years and 6 Months',
       '27 Years and 8 Months', '33 Years and 8 Months',
       '33 Years and 7 Months', '9 Years and 9 Months',
       '27 Years and 6 Months', '27 Years and 1 Months',
       '26 Years and 8 Months', '15 Years and 5 Months',
       '20 Years and 3 Months', '9 Years and 3 Months',
       '20 Years and 2 Months', '32 Years and 6 Months',
       '23 Years and 0 Months', '32 Years and 2 Months',
       '13 Years and 9 Months', '29 Years and 11 Months',
       '25 Years and 7 Months', '31 Years and 6 Months',
       '7 Years and 9 Months', '33 Years and 0 Months',
       '0 Years and 4 Months', '0 Years and 10 Months',
       '11 Years and 9 Months', '3 Years and 5 Months',
       '30 Years and 11 Months', '27 Years and 4 Months',
       '32 Years and 9 Months', '6 Years and 3 Months',
       '6 Years and 6 Months', '1 Years and 6 Months',
       '27 Years and 11 Months', '14 Years and 10 Months',
       '23 Years and 2 Months', '12 Years and 1 Months',
       '4 Years and 5 Months', '3 Years and 11 Months',
       '4 Years and 4 Months', '4 Years and 3 Months',
       '32 Years and 4 Months', '21 Years and 9 Months',
       '24 Years and 7 Months', '17 Years and 6 Months',
       '17 Years and 0 Months', '4 Years and 11 Months',
       '5 Years and 2 Months', '18 Years and 11 Months',
       '7 Years and 10 Months', '16 Years and 7 Months',
       '7 Years and 5 Months', '29 Years and 1 Months',
       '28 Years and 11 Months', '29 Years and 4 Months',
       '29 Years and 0 Months', '16 Years and 4 Months',
       '33 Years and 5 Months', '28 Years and 3 Months',
       '3 Years and 7 Months', '22 Years and 9 Months',
       '10 Years and 3 Months', '5 Years and 7 Months',
       '28 Years and 6 Months', '11 Years and 3 Months',
       '23 Years and 10 Months', '20 Years and 6 Months',
       '18 Years and 4 Months', '26 Years and 2 Months',
       '26 Years and 6 Months', '5 Years and 3 Months',
       '24 Years and 6 Months', '18 Years and 10 Months',
       '18 Years and 3 Months', '26 Years and 4 Months',
       '1 Years and 10 Months', '1 Years and 8 Months',
       '13 Years and 10 Months', '26 Years and 0 Months',
       '23 Years and 6 Months', '23 Years and 4 Months',
       '32 Years and 3 Months', '20 Years and 10 Months',
       '32 Years and 8 Months', '7 Years and 0 Months',
       '8 Years and 0 Months', '1 Years and 5 Months',
       '1 Years and 0 Months', '9 Years and 6 Months',
       '2 Years and 7 Months', '6 Years and 9 Months',
       '6 Years and 8 Months', '32 Years and 1 Months',
       '10 Years and 1 Months', '22 Years and 2 Months',
       '25 Years and 4 Months', '28 Years and 4 Months',
       '2 Years and 5 Months', '2 Years and 3 Months',
       '24 Years and 5 Months', '24 Years and 1 Months',
       '20 Years and 7 Months', '21 Years and 11 Months',
       '22 Years and 0 Months', '28 Years and 9 Months',
       '3 Years and 3 Months', '0 Years and 9 Months',
       '20 Years and 4 Months', '10 Years and 8 Months',
       '10 Years and 6 Months', '7 Years and 3 Months',
       '20 Years and 5 Months', '33 Years and 3 Months',
       '17 Years and 7 Months', '0 Years and 8 Months',
       '0 Years and 11 Months', '11 Years and 2 Months',
       '11 Years and 1 Months', '10 Years and 2 Months',
       '25 Years and 1 Months', '24 Years and 10 Months',
       '9 Years and 4 Months', '22 Years and 5 Months',
       '22 Years and 11 Months', '17 Years and 9 Months',
       '4 Years and 8 Months', '4 Years and 2 Months',
       '4 Years and 7 Months', '12 Years and 3 Months',
       '12 Years and 8 Months', '2 Years and 1 Months',
       '4 Years and 6 Months', '6 Years and 11 Months',
       '8 Years and 3 Months', '11 Years and 7 Months',
       '21 Years and 10 Months', '16 Years and 1 Months',
       '26 Years and 5 Months', '8 Years and 1 Months',
       '4 Years and 9 Months', '23 Years and 11 Months',
       '5 Years and 6 Months', '1 Years and 7 Months',
       '10 Years and 11 Months', '2 Years and 6 Months',
       '1 Years and 2 Months', '1 Years and 3 Months',
       '7 Years and 7 Months', '3 Years and 6 Months',
       '2 Years and 11 Months', '3 Years and 4 Months',
       '3 Years and 1 Months', '13 Years and 6 Months',
       '6 Years and 7 Months', '3 Years and 8 Months',
       '27 Years and 7 Months', '14 Years and 2 Months',
       '4 Years and 0 Months', '3 Years and 9 Months',
       '3 Years and 2 Months', '29 Years and 2 Months',
       '25 Years and 8 Months', '30 Years and 9 Months',
       '2 Years and 9 Months', '25 Years and 10 Months',
       '4 Years and 1 Months', '2 Years and 0 Months',
       '12 Years and 7 Months', '22 Years and 8 Months',
       '2 Years and 2 Months', '3 Years and 0 Months',
       '33 Years and 6 Months', '2 Years and 10 Months',
       '0 Years and 6 Months', '2 Years and 8 Months',
       '0 Years and 7 Months', '1 Years and 1 Months',
       '0 Years and 3 Months', '0 Years and 2 Months',
       '0 Years and 5 Months'], dtype=object)

In [208]:
temp = update_data['Credit_History_Age'].str.extract(r'(\d+)\s+Years?.*?(\d+)\s+Months?')

update_data['Credit_History_Age'] = (temp[0].astype(float)*12 + temp[1].astype(float))

In [209]:
update_data['Credit_History_Age']

0        129.0
1        124.0
2        365.0
3        183.0
4        187.0
         ...
19995    218.0
19996      NaN
19997    298.0
19998    219.0
19999    223.0
Name: Credit_History_Age, Length: 20000, dtype: float64

In [210]:
global_median = update_data['Credit_History_Age'].median()

update_data['Credit_History_Age'] = (
    update_data.groupby(['Customer_ID', 'Name'])['Credit_History_Age']
    .transform(lambda x: x.fillna(x.median()) if x.notna().any() else global_median)
)

# Check the number of nulls after imputation
print(f"Nulls in 'Credit_History_Age' after imputation: {update_data['Credit_History_Age'].isnull().sum()}")

Nulls in 'Credit_History_Age' after imputation: 0

Check Null that was transformed into 'NO_INFORM'

In [211]:
(update_data == 'NO_INFORM').sum()

ID                             0
Customer_ID                    0
Month                          0
Name                         503
Age                            0
SSN                            0
Occupation                     0
Annual_Income                  0
Monthly_Inhand_Salary          0
Num_Bank_Accounts              0
Num_Credit_Card                0
Interest_Rate                  0
Num_of_Loan                    0
Type_of_Loan                2195
Delay_from_due_date            0
Num_of_Delayed_Payment         0
Changed_Credit_Limit           0
Num_Credit_Inquiries           0
Credit_Mix                     0
Outstanding_Debt               0
Credit_Utilization_Ratio       0
Credit_History_Age             0
Payment_of_Min_Amount          0
Total_EMI_per_month            0
Amount_invested_monthly        0
Payment_Behaviour              0
Monthly_Balance                0
Credit_Score                   0
dtype: int64

In [212]:
c1 = data.loc[data['Type_of_Loan'].isna(), 'Name'].drop_duplicates().tolist()
c2 = update_data.loc[update_data['Type_of_Loan']=='NO_INFORM','Name'].drop_duplicates().tolist()

diff = set(c2) - set(c1)

print(list(diff))

# code ทำงานถูก แสดงว่าที่มันเป็น Null คือข้อมูล Type of Loan ของลูกค้าคนนั้นไม่ได้ถูกเก็บข้อมูลนั้นมาตั้งแต่แรก

['Clara FerreiraMarquesn', 'Nn', 'HerbstBaylisso', 'Svea HerbstBaylisst', 'Svea HerbstBaylissa', 'ChangRan Kimi', 'RobertJane', 'ChangRanj', ' Globalt', 'ShalalEsar', 'Steven Ca', 'Andrea ShalalEsap', 'Liana Bv', 'AlZaquanq', 'Ng', 'NO_INFORM', 'Nk', 'Andrea ShalalEsax', 'John ODonnellf', 'Andrea ShalalEsal', 'Andrea ShalalEsah', 'ODonnelly', 'YSingj', 'HerbstBaylissn', 'SaPintom', 'Martiny', 'Ag', 'Patrick TempleWestw', 'Steven Cr', 'Sarah Nv', 'HerbstBaylisst', 'Sarah Nt', 'John ODonnellh', 'Liana Br', 'Cr', 'OGradyg', 'ODonnello', 'Andrea ShalalEsac', 'Andrea ShalalEsag', 'FerreiraMarquesb', 'Joseph Aa', 'HerbstBaylissf', 'Helen NyamburaMwaurar', 'Sarah Nb']

Occupation

In [213]:
update_data['Occupation'] = update_data['Occupation'].replace('_______', np.nan)

update_data['Occupation'] = (
    update_data.groupby(['Customer_ID','Name'])['Occupation']
    .transform(lambda x: x.ffill().bfill())
)

update_data['Occupation'] = update_data['Occupation'].fillna('NO_INFORM')

Credit_Mix

In [214]:
update_data['Credit_Mix'] = (
    update_data['Credit_Mix']
    .replace('_', np.nan)
    .groupby([update_data['Customer_ID'], update_data['Name']])
    .ffill()
    .bfill()
    .fillna('NO_INFORM'))

Age

In [215]:
# Remove special characters (keep only digits)
update_data['Age'] = update_data['Age'].astype(str).str.replace(r'[^0-9]', '', regex=True)

# Convert to numeric
update_data['Age'] = pd.to_numeric(update_data['Age'], errors='coerce')

# Replace Age > 100 with median of the same person
update_data['Age'] = update_data.groupby(['Customer_ID','Name'])['Age'].transform(lambda x: x.mask(x > 100, x.median()))

Num_of_Loan

In [216]:
# Remove special characters (keep only digits)
update_data['Num_of_Loan'] = update_data['Num_of_Loan'].astype(str).str.replace(r'[^0-9]', '', regex=True)

# Convert to numeric
update_data['Num_of_Loan'] = pd.to_numeric(update_data['Num_of_Loan'], errors='coerce')

update_data['Num_of_Loan'] = update_data.groupby(['Customer_ID','Name'])['Num_of_Loan'].transform(lambda x: x.mask(x < 0, x.median()))

Changed_Credit_Limit

In [217]:
# 1. Replace '_' with NaN
update_data['Changed_Credit_Limit'] = update_data['Changed_Credit_Limit'].replace('_', np.nan)

# 2. Convert to numeric
update_data['Changed_Credit_Limit'] = pd.to_numeric(update_data['Changed_Credit_Limit'], errors='coerce')

# 3. Fill NaN with median of the same person
update_data['Changed_Credit_Limit'] = (
    update_data.groupby(['Customer_ID','Name'])['Changed_Credit_Limit']
    .transform(lambda x: x.fillna(x.median())))

# 4. If NaN still remains → fill with global median
global_median = update_data['Changed_Credit_Limit'].median()
update_data['Changed_Credit_Limit'] = update_data['Changed_Credit_Limit'].fillna(global_median)

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [218]:
update_data['Changed_Credit_Limit'].isna().sum()

0

Outstanding_Debt

In [219]:
# 1. Replace '_' with NaN
update_data['Outstanding_Debt'] = update_data['Outstanding_Debt'].replace('_', np.nan)

# 2. Convert to numeric
update_data['Outstanding_Debt'] = pd.to_numeric(update_data['Outstanding_Debt'], errors='coerce')

# 3. Fill NaN with median of the same person
update_data['Outstanding_Debt'] = (
    update_data.groupby(['Customer_ID','Name'])['Outstanding_Debt']
    .transform(lambda x: x.fillna(x.median())))

# 4. If NaN still remains → fill with global median
global_median = update_data['Outstanding_Debt'].median()
update_data['Outstanding_Debt'] = update_data['Outstanding_Debt'].fillna(global_median)

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\nanfunctions.py:1111: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [220]:
update_data['Outstanding_Debt'].isna().sum()

0

In [221]:
update_data[update_data['Outstanding_Debt'].isna()]

Empty DataFrame
Columns: [ID, Customer_ID, Month, Name, Age, SSN, Occupation, Annual_Income, Monthly_Inhand_Salary, Num_Bank_Accounts, Num_Credit_Card, Interest_Rate, Num_of_Loan, Type_of_Loan, Delay_from_due_date, Num_of_Delayed_Payment, Changed_Credit_Limit, Num_Credit_Inquiries, Credit_Mix, Outstanding_Debt, Credit_Utilization_Ratio, Credit_History_Age, Payment_of_Min_Amount, Total_EMI_per_month, Amount_invested_monthly, Payment_Behaviour, Monthly_Balance, Credit_Score]
Index: []

[0 rows x 28 columns]

Payment_Behaviour

In [222]:
# replace rows with special characters (except _) with NaN
update_data['Payment_Behaviour'] = update_data['Payment_Behaviour'].replace(r'[^A-Za-z_ ]', np.nan, regex=True)

# fill with closest value from the same person
update_data['Payment_Behaviour'] = (update_data.groupby(['Customer_ID','Name'])['Payment_Behaviour'].transform(lambda x: x.ffill().bfill()))

update_data['Payment_Behaviour'] = update_data['Payment_Behaviour'].fillna('NO_INFORM')

In [223]:
update_data['Payment_Behaviour'].isna().sum()

0

Annual_Income

In [224]:
# Remove special characters (keep only digits)
update_data['Annual_Income'] = update_data['Annual_Income'].astype(str).str.replace(r'[^0-9]', '', regex=True)

# Convert to numeric
update_data['Annual_Income'] = pd.to_numeric(update_data['Annual_Income'], errors='coerce')

update_data['Annual_Income'] = update_data.groupby(['Customer_ID','Name'])['Annual_Income'].transform(lambda x: x.mask(x < 0, x.median()))

Check Null

In [225]:
# check Null
check_null = pd.DataFrame(columns=['num_null', 'percent_null'])
check_null['num_null'] = update_data.isnull().sum()
check_null['percent_null'] = round(check_null['num_null'] / len(update_data) *100,2)
check_null

                          num_null  percent_null
ID                               0           0.0
Customer_ID                      0           0.0
Month                            0           0.0
Name                             0           0.0
Age                              0           0.0
SSN                              0           0.0
Occupation                       0           0.0
Annual_Income                    0           0.0
Monthly_Inhand_Salary            0           0.0
Num_Bank_Accounts                0           0.0
Num_Credit_Card                  0           0.0
Interest_Rate                    0           0.0
Num_of_Loan                      0           0.0
Type_of_Loan                     0           0.0
Delay_from_due_date              0           0.0
Num_of_Delayed_Payment           0           0.0
Changed_Credit_Limit             0           0.0
Num_Credit_Inquiries             0           0.0
Credit_Mix                       0           0.0
Outstanding_Debt                 0           0.0
Credit_Utilization_Ratio         0           0.0
Credit_History_Age               0           0.0
Payment_of_Min_Amount            0           0.0
Total_EMI_per_month              0           0.0
Amount_invested_monthly          0           0.0
Payment_Behaviour                0           0.0
Monthly_Balance                  0           0.0
Credit_Score                 20000         100.0

In [226]:
update_data.dtypes

ID                            int64
Customer_ID                  object
Month                        object
Name                         object
Age                         float64
SSN                          object
Occupation                   object
Annual_Income                 int64
Monthly_Inhand_Salary       float64
Num_Bank_Accounts             int64
Num_Credit_Card               int64
Interest_Rate                 int64
Num_of_Loan                   int64
Type_of_Loan                 object
Delay_from_due_date           int64
Num_of_Delayed_Payment      float64
Changed_Credit_Limit        float64
Num_Credit_Inquiries        float64
Credit_Mix                   object
Outstanding_Debt            float64
Credit_Utilization_Ratio    float64
Credit_History_Age          float64
Payment_of_Min_Amount        object
Total_EMI_per_month         float64
Amount_invested_monthly     float64
Payment_Behaviour            object
Monthly_Balance             float64
Credit_Score                float64
dtype: object

In [227]:
update_data.tail(5)

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
19995,19996,CUS_0xff4,January,Poornimaf,36.0,655-05-7666,Entrepreneur,2554626,2415.855000,8,...,Standard,758.44,37.418209,218.0,NM,101.328637,53.104599,High_spent_Medium_value_payments,337.152264,NaN
19996,19997,CUS_0xff4,June,Poornimaf,37.0,655-05-7666,Entrepreneur,2554626,2415.855000,8,...,Standard,758.44,34.586599,218.0,Yes,101.328637,61.730748,High_spent_Small_value_payments,338.526114,NaN
19997,19998,CUS_0xff6,July,Shieldsb,19.0,541-92-8371,Doctor,11763992,9727.326667,5,...,Good,338.30,23.631611,298.0,No,126.638453,1186.582604,Low_spent_Small_value_payments,337.531613,NaN
19998,19999,CUS_0xffd,February,Damouniq,29.0,832-88-8320,Scientist,4139844,3749.870000,8,...,Standard,1701.88,27.117338,219.0,Yes,182.976650,132.363348,Low_spent_Small_value_payments,349.647003,NaN
19999,20000,CUS_0xffd,June,Damouniq,29.0,832-88-8320,Scientist,4139844,3749.870000,8,...,Standard,1701.88,36.970072,223.0,Yes,182.976650,47.007379,High_spent_Medium_value_payments,395.002972,NaN

Standardize and One hot encoder

In [228]:
# separate X and y
X = update_data.drop(['ID', 'Customer_ID','Credit_Score','SSN'], axis=1)
# Y = update_data['Credit_Score']

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

# numeric columns
numeric_cols = X.select_dtypes(include=['int64','float64']).columns

# categorical columns
categorical_cols = X.select_dtypes(include='object').columns

# # preprocessing
# preprocess = ColumnTransformer(
#     transformers=[
#         ("num", StandardScaler(), numeric_cols),
#         ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
#     ]
# )

# # apply transformation
# X_processed2 = preprocess.fit_transform(X)

# feature_names = preprocess.get_feature_names_out()

In [230]:
X_processed2

<20000x13834 sparse matrix of type '<class 'numpy.float64'>'
	with 480000 stored elements in Compressed Sparse Row format>

In [232]:
import joblib

joblib.dump(X_processed2, "X_processed2.pkl")

['X_processed2.pkl']